### ISSUE TITLE
Error with file input

### ISSUE THREAD

**Issue by nik-steventon** [MRCIEU/GLU#2]
Hi,
I've had an issue with the code where for some reason my colleague is able to run the below script through his directory with the same set of files with no error, but when I use my PC I run into the error outlined in the screenshot below. 
Any ideas why this might be happening?

Please see attached screenshot for error and here is a copy of the code for reference:
#set data directory
DataDirectory = "C:/Users/Nik/Desktop/R Analysis- Nik"

#Complete days analysis
runGLUForDirectory(indir = paste0(DataDirectory, '/original'), 
                   outdir = paste0(DataDirectory, '/derived'),
                   device = 2, freq = 15, nightstart = '00:00')

![Error issue](https://user-images.githubusercontent.com/86938325/124408910-a053bd80-dd8a-11eb-8ffa-62dd10ff1bd9.PNG)

**Comment by louise** [comment]
Hi, Please could you supply a minimal working example (e.g. some made up data), so that I can try to recreate the issue? Feel free to email this to me at louise.millard@bristol.ac.uk.

BW, Louise

**Comment by louise** [comment]
I cannot recreate this issue with the data file you sent across. If this issue is still occuring then it would be good to have a minimal working example - i.e. reducing the size of the data file as much as possible to just the bit needed to reproduce the issue, so i can understand better what might be causing it. Also I would need to know the exact line in the data that is causing the issue (i.e. the line where, if you you remove it, then the error message doesn't occur).
